# This is a boilerplate parameters config generated for pipeline 'pathology_mass_prediction'
# using Kedro 0.16.5.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/stable/04_kedro_project_setup/02_configuration.html#parameters
