# This is a boilerplate parameters config generated for pipeline 'mammogram_mask_prediction'
# using Kedro 0.16.4.
#
# Documentation for this file format can be found in
# https://kedro.readthedocs.io/en/stable/04_user_guide/03_configuration.html#parameters
